Repository COSIMA/regional-mom6, pull requests merged in 2023-06, with the labels that each got.

#23 Delete `legacy_README.md` + updates `README.md`
  README.md
  legacy_README.md
Labels: cleanup 🧹

#36 Add black badge
  README.md
Labels: package 📦

#37 Remove placeholder `parabola` func/test
  mom6_regional/mom6_regional.py
  tests/test_trivial.py
Labels: testing 🧪

#38 Build API docs
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  mom6_regional/mom6_regional.py
Labels: documentation 📔

#34 Some cleanup
  demos/model-forced.ipynb
  demos/reanalysis-forced.ipynb
  mom6_regional/default_rundir/MOM_input
  mom6_regional/default_rundir/MOM_override
  mom6_regional/default_rundir/SIS_input
  mom6_regional/default_rundir/config.yaml
  mom6_regional/default_rundir/data_table
  mom6_regional/default_rundir/diag_table
  mom6_regional/default_rundir/env.yaml
  mom6_regional/default_rundir/era5_surface/MOM_input
  mom6_regional/default_rundir/era5_surface/MOM_override
  mom6_regional/default_rundir/era5_surface/README.md
  mom6_regional/default_rundir/era5_surface/SIS_input
  mom6_regional/default_rundir/era5_surface/config.yaml
  mom6_regional/default_rundir/era5_surface/data_table
  mom6_regional/default_rundir/era5_surface/diag_table
  mom6_regional/default_rundir/era5_surface/env.yaml
  mom6_regional/default_rundir/era5_surface/field_table
  mom6_regional/default_rundir/era5_surface/input.nml
  mom6_regional/default_rundir/era5_surface/job.yaml
  mom6_regional/default_rundir/field_table
  mom6_regional/default_rundir/input.nml
  mom6_regional/default_rundir/job.yaml
  mom6_regional/default_rundir/jra_surface/MOM_input
  mom6_regional/default_rundir/jra_surface/MOM_override
  mom6_regional/default_rundir/jra_surface/README.md
  mom6_regional/default_rundir/jra_surface/SIS_input
  mom6_regional/default_rundir/jra_surface/config.yaml
  mom6_regional/default_rundir/jra_surface/data_table
  mom6_regional/default_rundir/jra_surface/diag_table
  mom6_regional/default_rundir/jra_surface/env.yaml
  mom6_regional/default_rundir/jra_surface/field_table
  mom6_regional/default_rundir/jra_surface/input.nml
  mom6_regional/default_rundir/jra_surface/job.yaml
  regional_model_scripts.py
Labels: cleanup 🧹

#43 Add codecov.yml
  codecov.yml
Labels: package 📦

#44 Add instructions to run tests + build docs locally
  .gitignore
  docs/contributing.md
  docs/index.rst
Labels: documentation 📔

#47 Rename repo/package `mom6_regional` -> `regional_mom6`
  .github/workflows/testing.yml
  .gitignore
  LICENSE
  README.md
  demos/model-forced.ipynb
  demos/reanalysis-forced.ipynb
  docs/api.rst
  docs/conf.py
  docs/contributing.md
  docs/index.rst
  pyproject.toml
  regional_mom6/__init__.py
  regional_mom6/default_rundir/MOM_input
  regional_mom6/default_rundir/MOM_override
  regional_mom6/default_rundir/SIS_input
  regional_mom6/default_rundir/config.yaml
  regional_mom6/default_rundir/data_table
  regional_mom6/default_rundir/diag_table
  regional_mom6/default_rundir/env.yaml
  regional_mom6/default_rundir/era5_surface/MOM_input
  regional_mom6/default_rundir/era5_surface/MOM_override
  regional_mom6/default_rundir/era5_surface/README.md
  regional_mom6/default_rundir/era5_surface/SIS_input
  regional_mom6/default_rundir/era5_surface/config.yaml
  regional_mom6/default_rundir/era5_surface/data_table
  regional_mom6/default_rundir/era5_surface/diag_table
  regional_mom6/default_rundir/era5_surface/env.yaml
  regional_mom6/default_rundir/era5_surface/field_table
  regional_mom6/default_rundir/era5_surface/input.nml
  regional_mom6/default_rundir/era5_surface/job.yaml
  regional_mom6/default_rundir/field_table
  regional_mom6/default_rundir/input.nml
  regional_mom6/default_rundir/job.yaml
  regional_mom6/default_rundir/jra_surface/MOM_input
  regional_mom6/default_rundir/jra_surface/MOM_override
  regional_mom6/default_rundir/jra_surface/README.md
  regional_mom6/default_rundir/jra_surface/SIS_input
  regional_mom6/default_rundir/jra_surface/config.yaml
  regional_mom6/default_rundir/jra_surface/data_table
  regional_mom6/default_rundir/jra_surface/diag_table
  regional_mom6/default_rundir/jra_surface/env.yaml
  regional_mom6/default_rundir/jra_surface/field_table
  regional_mom6/default_rundir/jra_surface/input.nml
  regional_mom6/default_rundir/jra_surface/job.yaml
  regional_mom6/regional_mom6.py
  tests/test_trivial.py
Labels: package 📦

#49 Update instructions for local docs built
  docs/contributing.md
Labels: documentation 📔

#50 Add example with parametrized test
  tests/test_trivial.py
Labels: testing 🧪

#56 Add demo notebooks to docs
  demos/model-forced.ipynb
  demos/reanalysis-forced.ipynb
  docs/conf.py
  docs/demo_notebooks
  docs/demos.rst
  docs/index.rst
  docs/requirements.txt
Labels: documentation 📔

#54 Cleaner readme title
  README.md
Labels: package 📦
