Repository COSIMA/regional-mom6, pull requests merged in 2023-09, with the labels that each got.

#51 Some code cleanup
  .gitignore
  regional_mom6/regional_mom6.py
Labels: cleanup 🧹

#64 More verbose name for `quad_area` -> `quadrilateral_area` + one more test
  regional_mom6/regional_mom6.py
  tests/test_grid_generation.py
Labels: testing 🧪, cleanup 🧹

#66 Simplify quadilateral_area + better doc
  regional_mom6/regional_mom6.py
Labels: cleanup 🧹

#65 Simplify `angle_between` + refactor `quadrilateral_area`
  regional_mom6/regional_mom6.py
  regional_mom6/utils.py
  tests/test_grid_generation.py
Labels: cleanup 🧹

#71 Update codecov badge to point to `main` branch
  README.md
Labels: testing 🧪

#73 Replace ESMF subprocess calls with new parallel implementation of xesmf (0.8.x) directly in Python
  README.md
  demos/model-forced.ipynb
  demos/reanalysis-forced.ipynb
  pyproject.toml
  regional_mom6/default_rundir/MOM_input
  regional_mom6/default_rundir/MOM_override
  regional_mom6/default_rundir/SIS_input
  regional_mom6/default_rundir/config.yaml
  regional_mom6/default_rundir/data_table
  regional_mom6/default_rundir/diag_table
  regional_mom6/default_rundir/env.yaml
  regional_mom6/default_rundir/field_table
  regional_mom6/default_rundir/input.nml
  regional_mom6/default_rundir/job.yaml
  regional_mom6/regional_mom6.py
  tests/test_expt_class.py
Labels: bug 🐞
