Repository COSIMA/regional-mom6, pull requests merged in 2024-08, with the labels that each got.

#100 JOSS paper
  .github/workflows/testing.yml
  CITATION.cff
  README.md
  docs/index.rst
  paper/nested-regional-mom6.ipynb
  paper/nested-regional-mom6.pdf
  paper/paper.bib
  paper/paper.md
  paper/paper.pdf
Labels: joss 📓

#180 added glorys download functions with new API
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
Labels: user experience 📻

#182 Add link in the Docs pointing to the COSIMA recipe that uses the package
  docs/demos.rst
Labels: documentation 📔

#187 Better citation info in Docs
  docs/index.rst
Labels: documentation 📔
