Repository COSIMA/regional-mom6, pull requests merged in 2024-03, with the labels that each got.

#106 Clean up the vertical thickness profile generator (`dz_hyperbolictan`) + modify `_make_vgrid` to include `zi = 0`
  .gitignore
  demos/access_om2-forced.ipynb
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
  tests/test_grid_generation.py
Labels: documentation 📔, cleanup 🧹

#113 Revise `experiment` construction to utilize keyword arguments to enhance clarity
  demos/access_om2-forced.ipynb
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
  tests/test_expt_class.py
Labels: user experience 📻

#112 Enhance (and rename) `nicer_slicer` -> `longitude_slicer`
  demos/access_om2-forced.ipynb
  regional_mom6/regional_mom6.py
Labels: documentation 📔, cleanup 🧹

#124 Fix typo
  regional_mom6/regional_mom6.py
Labels: cleanup 🧹

#123 Tolerence of 10^-14 for even spacing too strict
  regional_mom6/regional_mom6.py
Labels: bug 🐞, cleanup 🧹

#126 Delete deprecated `motu_requests`
  regional_mom6/regional_mom6.py
Labels: cleanup 🧹

#125 Fix bug + test assertion error in `longitude_slicer`
  regional_mom6/regional_mom6.py
  tests/test_grid_generation.py
Labels: bug 🐞, testing 🧪

#122 Resolved a few errors in the example notebook
  demos/access_om2-forced.ipynb
  regional_mom6/regional_mom6.py
Labels: bug 🐞

#127 Ensure assumptions are met in `rectangular_hgrid`
  regional_mom6/regional_mom6.py
Labels: testing 🧪

#128 Better docstring rendering
  regional_mom6/regional_mom6.py
Labels: documentation 📔

#95 Update installation instructions
  .github/workflows/testing.yml
  README.md
  demos/premade_run_directories/readme_premade_rundirs.md
  demos/reanalysis-forced.ipynb
  docs/installation.md
  pyproject.toml
  regional_mom6/regional_mom6.py
Labels: documentation 📔

#139 Remove tide-related methods until proper tidal forcing implementation
  regional_mom6/regional_mom6.py
Labels: cleanup 🧹
