Repository COSIMA/regional-mom6, pull requests merged in 2024-04, with the labels that each got.

#136 Minor changes to readme
  README.md
  docs/installation.md
Labels: documentation 📔

#137 Further enhance/clarify `setup_run_directory`
  regional_mom6/regional_mom6.py
Labels: documentation 📔, user experience 📻

#144 JOSS paper edits/comments by Chris
  paper/paper.bib
  paper/paper.md
  paper/paper.pdf
Labels: joss 📓

#147 (0.5.0) Better `experiment.bathymetry` method
  demos/access_om2-forced.ipynb
  demos/premade_run_directories/common_files/SIS_input
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
  tests/test_expt_class.py
Labels: documentation 📔, user experience 📻

#148 Add intro in Docs + include a "MOM6 file structure primer" section
  README.md
  docs/index.rst
  docs/mom6-file-structure-primer.md
  regional_mom6/regional_mom6.py
Labels: documentation 📔, joss 📓

#153 Minor rephrase/format in the installation instructions
  README.md
  docs/installation.md
Labels: documentation 📔

#157 Docs edits
  README.md
  demos/premade_run_directories/README.md
  demos/premade_run_directories/readme_premade_rundirs.md
  docs/contributing.md
  docs/index.rst
  docs/installation.md
  docs/mom6-file-structure-primer.md
Labels: documentation 📔

#158 Tweak API docstrings/comments
  demos/access_om2-forced.ipynb
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
  regional_mom6/utils.py
  tests/test_expt_class.py
Labels: documentation 📔

#156 Show bathymetry plot in notebook + some other fixes
  demos/access_om2-forced.ipynb
  demos/reanalysis-forced.ipynb
  regional_mom6/regional_mom6.py
Labels: documentation 📔

#159 Few notebook fixes
  demos/access_om2-forced.ipynb
  demos/reanalysis-forced.ipynb
Labels: documentation 📔

#162 Delete ACCESS-OM2 example
  demos/access_om2-forced.ipynb
  docs/demos.rst
Labels: documentation 📔

#151 Automatic PyPI upload on GitHub release
  .github/workflows/package.yml
  pyproject.toml
Labels: package 📦

#167 fix regional-mom6 link in docs/index.rst
  docs/index.rst
Labels: documentation 📔

#163 Avoid singling out one contributor
  README.md
  docs/conf.py
  pyproject.toml
Labels: package 📦

#169 Add JOSS badge
  README.md
Labels: documentation 📔, joss 📓
